set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
foreach(pair "C;gcc" "CXX;g++" "RC;windres")
  list(GET pair 0 language)
  list(GET pair 1 program)
  if(NOT CMAKE_${language}_COMPILER)
    find_program(CMAKE_${language}_COMPILER NAMES x86_64-w64-mingw32-${program} REQUIRED)
  endif()
endforeach()

# GCC knows its installation layout, including relocated toolchains. Fedora
# puts target headers/libraries under sys-root/mingw; Debian uses the root.
if(NOT CMAKE_SYSROOT AND DEFINED ENV{MINGW_SYSROOT})
  set(CMAKE_SYSROOT "$ENV{MINGW_SYSROOT}")
endif()
if(NOT CMAKE_SYSROOT)
  execute_process(COMMAND "${CMAKE_C_COMPILER}" -print-sysroot
    OUTPUT_VARIABLE target_root OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE probe_result)
  if(probe_result EQUAL 0 AND IS_DIRECTORY "${target_root}")
    set(CMAKE_SYSROOT "${target_root}")
  else()
    get_filename_component(compiler_bin "${CMAKE_C_COMPILER}" DIRECTORY)
    get_filename_component(compiler_prefix "${compiler_bin}" DIRECTORY)
    if(IS_DIRECTORY "${compiler_prefix}/x86_64-w64-mingw32")
      set(CMAKE_FIND_ROOT_PATH "${compiler_prefix}/x86_64-w64-mingw32")
    else()
      message(FATAL_ERROR "Cannot locate MinGW target libraries. Set MINGW_SYSROOT to the Windows target root.")
    endif()
  endif()
endif()
if(CMAKE_SYSROOT)
  if(NOT IS_DIRECTORY "${CMAKE_SYSROOT}")
    message(FATAL_ERROR "MINGW_SYSROOT does not exist: ${CMAKE_SYSROOT}")
  endif()
  set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}/mingw" "${CMAKE_SYSROOT}")
endif()
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
# pkg-config must never return native Linux libraries to a Windows build.
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "")
foreach(root IN LISTS CMAKE_FIND_ROOT_PATH)
  if(IS_DIRECTORY "${root}/lib/pkgconfig")
    if(NOT "$ENV{PKG_CONFIG_LIBDIR}" STREQUAL "")
      set(ENV{PKG_CONFIG_LIBDIR} "$ENV{PKG_CONFIG_LIBDIR}:${root}/lib/pkgconfig")
    else()
      set(ENV{PKG_CONFIG_LIBDIR} "${root}/lib/pkgconfig")
    endif()
  endif()
endforeach()
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${CMAKE_SYSROOT}")
